<?php
/**
 * CallEndedReason
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FreeClimb\Api\Model;
use \FreeClimb\Api\ObjectSerializer;

/**
 * CallEndedReason Class Doc Comment
 *
 * @category Class
 * @description Enhanced status for the Call with additional information where available.
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CallEndedReason
{
    /**
     * Possible values of this enum
     */
    const BUSY = 'busy';

    const FAILED = 'failed';

    const NO_ANSWER = 'noAnswer';

    const CALL_CANCELED = 'callCanceled';

    const FAR_END_HANGUP = 'farEndHangup';

    const APP_HANGUP = 'appHangup';

    const APP_REJECT = 'appReject';

    const APP_NO_PERCL = 'appNoPercl';

    const APP_INVALID_PERCL = 'appInvalidPercl';

    const CONFERENCE_TERMINATED = 'conferenceTerminated';

    const CONFERENCE_EMPTIED = 'conferenceEmptied';

    const REMOVED_FROM_CONFERENCE = 'removedFromConference';

    const MACHINE_DETECTED = 'machineDetected';

    const WEBHOOK_FAILED = 'webhookFailed';

    const WEBHOOK_INVALID_RESPONSE = 'webhookInvalidResponse';

    const VOICE_DISABLED = 'voiceDisabled';

    const CONFIG_ERROR_NO_APPLICATION = 'configErrorNoApplication';

    const CONFIG_ERROR_NO_VOICE_URL = 'configErrorNoVoiceUrl';

    const MAX_REDIRECTS_ERROR = 'maxRedirectsError';

    const PERCL_PROCESSING_ERROR = 'perclProcessingError';

    const INTERNAL_ERROR = 'internalError';

    const GRPC_HANGUP = 'grpcHangup';

    const MAX_DURATION = 'maxDuration';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BUSY,
            self::FAILED,
            self::NO_ANSWER,
            self::CALL_CANCELED,
            self::FAR_END_HANGUP,
            self::APP_HANGUP,
            self::APP_REJECT,
            self::APP_NO_PERCL,
            self::APP_INVALID_PERCL,
            self::CONFERENCE_TERMINATED,
            self::CONFERENCE_EMPTIED,
            self::REMOVED_FROM_CONFERENCE,
            self::MACHINE_DETECTED,
            self::WEBHOOK_FAILED,
            self::WEBHOOK_INVALID_RESPONSE,
            self::VOICE_DISABLED,
            self::CONFIG_ERROR_NO_APPLICATION,
            self::CONFIG_ERROR_NO_VOICE_URL,
            self::MAX_REDIRECTS_ERROR,
            self::PERCL_PROCESSING_ERROR,
            self::INTERNAL_ERROR,
            self::GRPC_HANGUP,
            self::MAX_DURATION
        ];
    }
}


