<?php
/**
 * RecordWebhook
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FreeClimb\Api\Model;
use \FreeClimb\Api\ObjectSerializer;

/**
 * RecordWebhook Class Doc Comment
 *
 * @category Class
 * @description The RecordUtterance command has completed and its actionUrl is being invoked.
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class RecordWebhook extends Webhook
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RecordWebhook';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'request_type' => 'string',
        'account_id' => 'string',
        'call_id' => 'string',
        'from' => 'string',
        'to' => 'string',
        'call_status' => '\FreeClimb\Api\Model\CallStatus',
        'direction' => '\FreeClimb\Api\Model\CallDirection',
        'conference_id' => 'string',
        'queue_id' => 'string',
        'recording_id' => 'string',
        'recording_url' => 'string',
        'recording_size' => 'string',
        'recording_format' => 'string',
        'recording_duration_sec' => 'int',
        'term_reason' => '\FreeClimb\Api\Model\RecordUtteranceTermReason',
        'parent_call_id' => 'string',
        'privacy_mode' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'request_type' => null,
        'account_id' => null,
        'call_id' => null,
        'from' => null,
        'to' => null,
        'call_status' => null,
        'direction' => null,
        'conference_id' => null,
        'queue_id' => null,
        'recording_id' => null,
        'recording_url' => null,
        'recording_size' => null,
        'recording_format' => null,
        'recording_duration_sec' => null,
        'term_reason' => null,
        'parent_call_id' => null,
        'privacy_mode' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes + parent::openAPITypes();
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats + parent::openAPIFormats();
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'request_type' => 'requestType',
        'account_id' => 'accountId',
        'call_id' => 'callId',
        'from' => 'from',
        'to' => 'to',
        'call_status' => 'callStatus',
        'direction' => 'direction',
        'conference_id' => 'conferenceId',
        'queue_id' => 'queueId',
        'recording_id' => 'recordingId',
        'recording_url' => 'recordingUrl',
        'recording_size' => 'recordingSize',
        'recording_format' => 'recordingFormat',
        'recording_duration_sec' => 'recordingDurationSec',
        'term_reason' => 'termReason',
        'parent_call_id' => 'parentCallId',
        'privacy_mode' => 'privacyMode'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'request_type' => 'setRequestType',
        'account_id' => 'setAccountId',
        'call_id' => 'setCallId',
        'from' => 'setFrom',
        'to' => 'setTo',
        'call_status' => 'setCallStatus',
        'direction' => 'setDirection',
        'conference_id' => 'setConferenceId',
        'queue_id' => 'setQueueId',
        'recording_id' => 'setRecordingId',
        'recording_url' => 'setRecordingUrl',
        'recording_size' => 'setRecordingSize',
        'recording_format' => 'setRecordingFormat',
        'recording_duration_sec' => 'setRecordingDurationSec',
        'term_reason' => 'setTermReason',
        'parent_call_id' => 'setParentCallId',
        'privacy_mode' => 'setPrivacyMode'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'request_type' => 'getRequestType',
        'account_id' => 'getAccountId',
        'call_id' => 'getCallId',
        'from' => 'getFrom',
        'to' => 'getTo',
        'call_status' => 'getCallStatus',
        'direction' => 'getDirection',
        'conference_id' => 'getConferenceId',
        'queue_id' => 'getQueueId',
        'recording_id' => 'getRecordingId',
        'recording_url' => 'getRecordingUrl',
        'recording_size' => 'getRecordingSize',
        'recording_format' => 'getRecordingFormat',
        'recording_duration_sec' => 'getRecordingDurationSec',
        'term_reason' => 'getTermReason',
        'parent_call_id' => 'getParentCallId',
        'privacy_mode' => 'getPrivacyMode'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return parent::attributeMap() + self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return parent::setters() + self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return parent::getters() + self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }



    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        parent::__construct($data);

        $this->container['request_type'] = $data['request_type'] ?? null;
        $this->container['account_id'] = $data['account_id'] ?? null;
        $this->container['call_id'] = $data['call_id'] ?? null;
        $this->container['from'] = $data['from'] ?? null;
        $this->container['to'] = $data['to'] ?? null;
        $this->container['call_status'] = $data['call_status'] ?? null;
        $this->container['direction'] = $data['direction'] ?? null;
        $this->container['conference_id'] = $data['conference_id'] ?? null;
        $this->container['queue_id'] = $data['queue_id'] ?? null;
        $this->container['recording_id'] = $data['recording_id'] ?? null;
        $this->container['recording_url'] = $data['recording_url'] ?? null;
        $this->container['recording_size'] = $data['recording_size'] ?? null;
        $this->container['recording_format'] = $data['recording_format'] ?? null;
        $this->container['recording_duration_sec'] = $data['recording_duration_sec'] ?? null;
        $this->container['term_reason'] = $data['term_reason'] ?? null;
        $this->container['parent_call_id'] = $data['parent_call_id'] ?? null;
        $this->container['privacy_mode'] = $data['privacy_mode'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets request_type
     *
     * @return string|null
     */
    public function getRequestType()
    {
        return $this->container['request_type'];
    }

    /**
     * Sets request_type
     *
     * @param string|null $request_type The context or reason why this request is being made. Will be record - The RecordUtterance command has completed and its actionUrl is being invoked.
     *
     * @return self
     */
    public function setRequestType($request_type)
    {
        $this->container['request_type'] = $request_type;

        return $this;
    }

    /**
     * Gets account_id
     *
     * @return string|null
     */
    public function getAccountId()
    {
        return $this->container['account_id'];
    }

    /**
     * Sets account_id
     *
     * @param string|null $account_id Account ID associated with your account.
     *
     * @return self
     */
    public function setAccountId($account_id)
    {
        $this->container['account_id'] = $account_id;

        return $this;
    }

    /**
     * Gets call_id
     *
     * @return string|null
     */
    public function getCallId()
    {
        return $this->container['call_id'];
    }

    /**
     * Sets call_id
     *
     * @param string|null $call_id Unique identifier for this Call, generated by FreeClimb
     *
     * @return self
     */
    public function setCallId($call_id)
    {
        $this->container['call_id'] = $call_id;

        return $this;
    }

    /**
     * Gets from
     *
     * @return string|null
     */
    public function getFrom()
    {
        return $this->container['from'];
    }

    /**
     * Sets from
     *
     * @param string|null $from Phone number of the party that initiated the Call (in E.164 format).
     *
     * @return self
     */
    public function setFrom($from)
    {
        $this->container['from'] = $from;

        return $this;
    }

    /**
     * Gets to
     *
     * @return string|null
     */
    public function getTo()
    {
        return $this->container['to'];
    }

    /**
     * Sets to
     *
     * @param string|null $to Phone number provisioned to the customer and to which this Call is directed (in E.164 format).
     *
     * @return self
     */
    public function setTo($to)
    {
        $this->container['to'] = $to;

        return $this;
    }

    /**
     * Gets call_status
     *
     * @return \FreeClimb\Api\Model\CallStatus|null
     */
    public function getCallStatus()
    {
        return $this->container['call_status'];
    }

    /**
     * Sets call_status
     *
     * @param \FreeClimb\Api\Model\CallStatus|null $call_status call_status
     *
     * @return self
     */
    public function setCallStatus($call_status)
    {
        $this->container['call_status'] = $call_status;

        return $this;
    }

    /**
     * Gets direction
     *
     * @return \FreeClimb\Api\Model\CallDirection|null
     */
    public function getDirection()
    {
        return $this->container['direction'];
    }

    /**
     * Sets direction
     *
     * @param \FreeClimb\Api\Model\CallDirection|null $direction direction
     *
     * @return self
     */
    public function setDirection($direction)
    {
        $this->container['direction'] = $direction;

        return $this;
    }

    /**
     * Gets conference_id
     *
     * @return string|null
     */
    public function getConferenceId()
    {
        return $this->container['conference_id'];
    }

    /**
     * Sets conference_id
     *
     * @param string|null $conference_id This is only populated if request pertains to a conference. Otherwise, it is set to null.
     *
     * @return self
     */
    public function setConferenceId($conference_id)
    {
        $this->container['conference_id'] = $conference_id;

        return $this;
    }

    /**
     * Gets queue_id
     *
     * @return string|null
     */
    public function getQueueId()
    {
        return $this->container['queue_id'];
    }

    /**
     * Sets queue_id
     *
     * @param string|null $queue_id This is only populated if the request pertains to a queue. Otherwise, it is set to null.
     *
     * @return self
     */
    public function setQueueId($queue_id)
    {
        $this->container['queue_id'] = $queue_id;

        return $this;
    }

    /**
     * Gets recording_id
     *
     * @return string|null
     */
    public function getRecordingId()
    {
        return $this->container['recording_id'];
    }

    /**
     * Sets recording_id
     *
     * @param string|null $recording_id ID of the recording.
     *
     * @return self
     */
    public function setRecordingId($recording_id)
    {
        $this->container['recording_id'] = $recording_id;

        return $this;
    }

    /**
     * Gets recording_url
     *
     * @return string|null
     */
    public function getRecordingUrl()
    {
        return $this->container['recording_url'];
    }

    /**
     * Sets recording_url
     *
     * @param string|null $recording_url URL of the recorded audio file. This URL can be used as is in a Play command to play the recording (no authentication needed). It can also be used to download a recording file via the REST API.
     *
     * @return self
     */
    public function setRecordingUrl($recording_url)
    {
        $this->container['recording_url'] = $recording_url;

        return $this;
    }

    /**
     * Gets recording_size
     *
     * @return string|null
     */
    public function getRecordingSize()
    {
        return $this->container['recording_size'];
    }

    /**
     * Sets recording_size
     *
     * @param string|null $recording_size Size of the recording in bytes
     *
     * @return self
     */
    public function setRecordingSize($recording_size)
    {
        $this->container['recording_size'] = $recording_size;

        return $this;
    }

    /**
     * Gets recording_format
     *
     * @return string|null
     */
    public function getRecordingFormat()
    {
        return $this->container['recording_format'];
    }

    /**
     * Sets recording_format
     *
     * @param string|null $recording_format File type of the recording (audio/wav)
     *
     * @return self
     */
    public function setRecordingFormat($recording_format)
    {
        $this->container['recording_format'] = $recording_format;

        return $this;
    }

    /**
     * Gets recording_duration_sec
     *
     * @return int|null
     */
    public function getRecordingDurationSec()
    {
        return $this->container['recording_duration_sec'];
    }

    /**
     * Sets recording_duration_sec
     *
     * @param int|null $recording_duration_sec Duration of the recorded audio rounded up to the nearest second (in seconds)
     *
     * @return self
     */
    public function setRecordingDurationSec($recording_duration_sec)
    {
        $this->container['recording_duration_sec'] = $recording_duration_sec;

        return $this;
    }

    /**
     * Gets term_reason
     *
     * @return \FreeClimb\Api\Model\RecordUtteranceTermReason|null
     */
    public function getTermReason()
    {
        return $this->container['term_reason'];
    }

    /**
     * Sets term_reason
     *
     * @param \FreeClimb\Api\Model\RecordUtteranceTermReason|null $term_reason term_reason
     *
     * @return self
     */
    public function setTermReason($term_reason)
    {
        $this->container['term_reason'] = $term_reason;

        return $this;
    }

    /**
     * Gets parent_call_id
     *
     * @return string|null
     */
    public function getParentCallId()
    {
        return $this->container['parent_call_id'];
    }

    /**
     * Sets parent_call_id
     *
     * @param string|null $parent_call_id ID of Call that created this leg (child call).
     *
     * @return self
     */
    public function setParentCallId($parent_call_id)
    {
        $this->container['parent_call_id'] = $parent_call_id;

        return $this;
    }

    /**
     * Gets privacy_mode
     *
     * @return bool|null
     */
    public function getPrivacyMode()
    {
        return $this->container['privacy_mode'];
    }

    /**
     * Sets privacy_mode
     *
     * @param bool|null $privacy_mode If true then it indicates the recording will only be available for download for two minutes prior to it being deleted. This is to minimize risk of anyone else getting access to the url and attempting to access it.
     *
     * @return self
     */
    public function setPrivacyMode($privacy_mode)
    {
        $this->container['privacy_mode'] = $privacy_mode;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset) : bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset) : mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value) : void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset) : void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize() : mixed
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString() : string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue() : string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }

}


