<?php

/**
 * SayStandardCulture
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FreeClimb\Api\Model;
use \FreeClimb\Api\ObjectSerializer;

/**
 * SayStandardCulture Class Doc Comment
 *
 * @category Class
 * @description The culture to use for the TTS. The complete list of valid values for the culture attribute is shown below.
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SayStandardCulture
{
    /**
     * Possible values of this enum
     */
    public const CA_ES = "ca-ES";
    public const DA_DK = "da-DK";
    public const DE_DE = "de-DE";
    public const EN_AU = "en-AU";
    public const EN_CA = "en-CA";
    public const EN_GB = "en-GB";
    public const EN_IN = "en-IN";
    public const EN_US = "en-US";
    public const ES_ES = "es-ES";
    public const ES_MX = "es-MX";
    public const FI_FI = "fi-FI";
    public const FR_CA = "fr-CA";
    public const FR_FR = "fr-FR";
    public const IT_IT = "it-IT";
    public const JA_JP = "ja-JP";
    public const KO_KR = "ko-KR";
    public const NB_NO = "nb-NO";
    public const NL_NL = "nl-NL";
    public const PL_PL = "pl-PL";
    public const PT_BR = "pt-BR";
    public const PT_PT = "pt-PT";
    public const RU_RU = "ru-RU";
    public const SV_SE = "sv-SE";
    public const ZH_CN = "zh-CN";
    public const ZH_HK = "zh-HK";
    public const ZH_TW = "zh-TW";


    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [

            self::CA_ES,
            self::DA_DK,
            self::DE_DE,
            self::EN_AU,
            self::EN_CA,
            self::EN_GB,
            self::EN_IN,
            self::EN_US,
            self::ES_ES,
            self::ES_MX,
            self::FI_FI,
            self::FR_CA,
            self::FR_FR,
            self::IT_IT,
            self::JA_JP,
            self::KO_KR,
            self::NB_NO,
            self::NL_NL,
            self::PL_PL,
            self::PT_BR,
            self::PT_PT,
            self::RU_RU,
            self::SV_SE,
            self::ZH_CN,
            self::ZH_HK,
            self::ZH_TW
        ];
    }
}


