<?php
/**
 * SMSTenDLCBrandStockExchange
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FreeClimb\Api\Model;
use \FreeClimb\Api\ObjectSerializer;

/**
 * SMSTenDLCBrandStockExchange Class Doc Comment
 *
 * @category Class
 * @description (Required for public company) stock exchange.
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SMSTenDLCBrandStockExchange
{
    /**
     * Possible values of this enum
     */
    const NONE = 'NONE';

    const NASDAQ = 'NASDAQ';

    const NYSE = 'NYSE';

    const AMEX = 'AMEX';

    const AMX = 'AMX';

    const ASX = 'ASX';

    const B3 = 'B3';

    const BME = 'BME';

    const BSE = 'BSE';

    const FRA = 'FRA';

    const ICEX = 'ICEX';

    const JPX = 'JPX';

    const JSE = 'JSE';

    const KRX = 'KRX';

    const LON = 'LON';

    const NSE = 'NSE';

    const OMX = 'OMX';

    const SEHK = 'SEHK';

    const SGX = 'SGX';

    const SSE = 'SSE';

    const STO = 'STO';

    const SWX = 'SWX';

    const SZSE = 'SZSE';

    const TSX = 'TSX';

    const TWSE = 'TWSE';

    const VSE = 'VSE';

    const OTHER = 'OTHER';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NONE,
            self::NASDAQ,
            self::NYSE,
            self::AMEX,
            self::AMX,
            self::ASX,
            self::B3,
            self::BME,
            self::BSE,
            self::FRA,
            self::ICEX,
            self::JPX,
            self::JSE,
            self::KRX,
            self::LON,
            self::NSE,
            self::OMX,
            self::SEHK,
            self::SGX,
            self::SSE,
            self::STO,
            self::SWX,
            self::SZSE,
            self::TSX,
            self::TWSE,
            self::VSE,
            self::OTHER
        ];
    }
}


