<?php

/**
 * AccountResultAllOfTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto-generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb\Api\Test\Model;

use FreeClimb\Api\Model\AccountResultAllOf;
use PHPUnit\Framework\TestCase;

/**
 * AccountResultAllOfTest Class Doc Comment
 *
 * @category    Class
 * @description AccountResultAllOf
 * @package     FreeClimb\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AccountResultAllOfTest extends TestCase
{
    protected $AccountResultAllOf;

    /**
     * Test "AccountResultAllOf"
     */
    public function setUp() : void
    {
        $this->AccountResultAllOf = new AccountResultAllOf();
    }
    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
        $this->AccountResultAllOf->setAccountId('TS');
        $this->assertEquals('TS', $this->AccountResultAllOf->getAccountId());
        $this->assertIsString($this->AccountResultAllOf->getAccountId());
    }
    /**
     * Test attribute "api_key"
     */
    public function testPropertyApiKey()
    {
        $this->AccountResultAllOf->setApiKey('TS');
        $this->assertEquals('TS', $this->AccountResultAllOf->getApiKey());
        $this->assertIsString($this->AccountResultAllOf->getApiKey());
    }
    /**
     * Test attribute "alias"
     */
    public function testPropertyAlias()
    {
        $this->AccountResultAllOf->setAlias('TS');
        $this->assertEquals('TS', $this->AccountResultAllOf->getAlias());
        $this->assertIsString($this->AccountResultAllOf->getAlias());
    }
    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {
        $this->AccountResultAllOf->setLabel('TS');
        $this->assertEquals('TS', $this->AccountResultAllOf->getLabel());
        $this->assertIsString($this->AccountResultAllOf->getLabel());
    }
    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        $this->AccountResultAllOf->setType(\FreeClimb\Api\Model\AccountType::TRIAL);
        $this->assertEquals(\FreeClimb\Api\Model\AccountType::TRIAL, $this->AccountResultAllOf->getType());
        $this->AccountResultAllOf->setType(\FreeClimb\Api\Model\AccountType::FULL);
        $this->assertEquals(\FreeClimb\Api\Model\AccountType::FULL, $this->AccountResultAllOf->getType());
    }
    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
        $this->AccountResultAllOf->setStatus(\FreeClimb\Api\Model\AccountStatus::CLOSED);
        $this->assertEquals(\FreeClimb\Api\Model\AccountStatus::CLOSED, $this->AccountResultAllOf->getStatus());
        $this->AccountResultAllOf->setStatus(\FreeClimb\Api\Model\AccountStatus::SUSPENDED);
        $this->assertEquals(\FreeClimb\Api\Model\AccountStatus::SUSPENDED, $this->AccountResultAllOf->getStatus());
        $this->AccountResultAllOf->setStatus(\FreeClimb\Api\Model\AccountStatus::ACTIVE);
        $this->assertEquals(\FreeClimb\Api\Model\AccountStatus::ACTIVE, $this->AccountResultAllOf->getStatus());
    }
    /**
     * Test attribute "subresource_uris"
     */
    public function testPropertySubresourceUris()
    {
        $this->AccountResultAllOf->setSubresourceUris(new \stdClass);
        $this->assertInstanceOf(\stdClass::class, $this->AccountResultAllOf->getSubresourceUris());
    }

    /**
* Test method toStringTest
*/
public function toStringTest() {
    $test1 = new AccountResultAllOf();    
    $test1->setAccountId("TS");
    $test1->setApiKey("TS");
    $test1->setAlias("TS");
    $test1->setLabel("TS");
    $test1->setType(\FreeClimb\Api\Model\AccountType::TRIAL);
    $test1->setStatus(\FreeClimb\Api\Model\AccountStatus::CLOSED);
    $testObject = new stdClass(); 
    $test1->setSubresourceUris($testObject);

    $toString1 = $test1->__toString();
    assert(is_string($toString1));
}

/**
 * Test method toHeaderValue
 */
public function toHeaderValueTest()
{
    $test1 = new AccountResultAllOf();
    $test1->setAccountId("TS");
    $test1->setApiKey("TS");
    $test1->setAlias("TS");
    $test1->setLabel("TS");
    $test1->setType(\FreeClimb\Api\Model\AccountType::TRIAL);
    $test1->setStatus(\FreeClimb\Api\Model\AccountStatus::CLOSED);
    $testObject = new stdClass();
    $test1->setSubresourceUris($testObject);

    $toHeaderValue1 = $test1->toHeaderValue();
    assert(is_string($toHeaderValue1));
}


}
