<?php

/**
 * AudioStreamWebhookTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb\Api\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AudioStreamWebhookTest Class Doc Comment
 *
 * @category    Class
 * @description A gRPC session has ended for this Call its actionUrl is being invoked. A PerCL response is expected — unless the URL is invoked due to the participant hanging up.
 * @package     FreeClimb\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
#[\AllowDynamicProperties]
class AudioStreamWebhookTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $this->AudioStreamWebhook = new \FreeClimb\Api\Model\AudioStreamWebhook();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }


    public function testPropertyRequestType()
    {

        $this->AudioStreamWebhook->setRequestType('TS');
        $this->assertEquals('TS', $this->AudioStreamWebhook->getRequestType());
        $this->assertIsString($this->AudioStreamWebhook->getRequestType());
    }

    public function testPropertyCallId()
    {

        $this->AudioStreamWebhook->setCallId('TS');
        $this->assertEquals('TS', $this->AudioStreamWebhook->getCallId());
        $this->assertIsString($this->AudioStreamWebhook->getCallId());
    }

    public function testPropertyAccountId()
    {

        $this->AudioStreamWebhook->setAccountId('TS');
        $this->assertEquals('TS', $this->AudioStreamWebhook->getAccountId());
        $this->assertIsString($this->AudioStreamWebhook->getAccountId());
    }

    public function testPropertyFrom()
    {

        $this->AudioStreamWebhook->setFrom('TS');
        $this->assertEquals('TS', $this->AudioStreamWebhook->getFrom());
        $this->assertIsString($this->AudioStreamWebhook->getFrom());
    }

    public function testPropertyTo()
    {

        $this->AudioStreamWebhook->setTo('TS');
        $this->assertEquals('TS', $this->AudioStreamWebhook->getTo());
        $this->assertIsString($this->AudioStreamWebhook->getTo());
    }

    public function testPropertyCallStatus()
    {
        $this->AudioStreamWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::QUEUED);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::QUEUED, $this->AudioStreamWebhook->getcallStatus());
        $this->AudioStreamWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::RINGING);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::RINGING, $this->AudioStreamWebhook->getcallStatus());
        $this->AudioStreamWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::IN_PROGRESS);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::IN_PROGRESS, $this->AudioStreamWebhook->getcallStatus());
        $this->AudioStreamWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::CANCELED);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::CANCELED, $this->AudioStreamWebhook->getcallStatus());
        $this->AudioStreamWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::COMPLETED);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::COMPLETED, $this->AudioStreamWebhook->getcallStatus());
        $this->AudioStreamWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::FAILED);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::FAILED, $this->AudioStreamWebhook->getcallStatus());
        $this->AudioStreamWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::BUSY);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::BUSY, $this->AudioStreamWebhook->getcallStatus());
        $this->AudioStreamWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::NO_ANSWER);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::NO_ANSWER, $this->AudioStreamWebhook->getcallStatus());
    }

    public function testPropertyDirection()
    {
        $this->AudioStreamWebhook->setdirection(\FreeClimb\Api\Model\CallDirection::INBOUND);
        $this->assertEquals(\FreeClimb\Api\Model\CallDirection::INBOUND, $this->AudioStreamWebhook->getdirection());
        $this->AudioStreamWebhook->setdirection(\FreeClimb\Api\Model\CallDirection::OUTBOUND_API);
        $this->assertEquals(\FreeClimb\Api\Model\CallDirection::OUTBOUND_API, $this->AudioStreamWebhook->getdirection());
        $this->AudioStreamWebhook->setdirection(\FreeClimb\Api\Model\CallDirection::OUTBOUND_DIAL);
        $this->assertEquals(\FreeClimb\Api\Model\CallDirection::OUTBOUND_DIAL, $this->AudioStreamWebhook->getdirection());
    }

    public function testPropertyConferenceId()
    {

        $this->AudioStreamWebhook->setConferenceId('TS');
        $this->assertEquals('TS', $this->AudioStreamWebhook->getConferenceId());
        $this->assertIsString($this->AudioStreamWebhook->getConferenceId());
    }

    public function testPropertyQueueId()
    {

        $this->AudioStreamWebhook->setQueueId('TS');
        $this->assertEquals('TS', $this->AudioStreamWebhook->getQueueId());
        $this->assertIsString($this->AudioStreamWebhook->getQueueId());
    }
    /**
     * Test attribute "AudioStreamWebhook::deserialize"
     */
    public function testDeserializeAudioStreamWebhook()
    {
        $json = "{\"requestType\":\"audioStream\"}";
        $this->assertInstanceOf(\FreeClimb\Api\Model\AudioStreamWebhook::class, \FreeClimb\Api\Model\AudioStreamWebhook::deserialize($json));
    }
}
