<?php

/**
 * CallResultTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto-generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb\Api\Test\Model;

use FreeClimb\Api\Model\CallResult;
use PHPUnit\Framework\TestCase;

/**
 * CallResultTest Class Doc Comment
 *
 * @category    Class
 * @description CallResult
 * @package     FreeClimb\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CallResultTest extends TestCase
{
    protected $CallResult;

    /**
     * Test "CallResult"
     */
    public function setUp() : void
    {
        $this->CallResult = new CallResult();
    }
    /**
     * Test attribute "uri"
     */
    public function testPropertyUri()
    {
        $this->CallResult->setUri('TEST_STRING');
        $this->assertEquals('TEST_STRING', $this->CallResult->getUri());
        $this->assertIsString($this->CallResult->getUri());
        

    }
    /**
     * Test attribute "date_created"
     */
    public function testPropertyDateCreated()
    {
        $this->CallResult->setDateCreated('TEST_STRING');
        $this->assertEquals('TEST_STRING', $this->CallResult->getDateCreated());
        $this->assertIsString($this->CallResult->getDateCreated());
        

    }
    /**
     * Test attribute "date_updated"
     */
    public function testPropertyDateUpdated()
    {
        $this->CallResult->setDateUpdated('TEST_STRING');
        $this->assertEquals('TEST_STRING', $this->CallResult->getDateUpdated());
        $this->assertIsString($this->CallResult->getDateUpdated());
        

    }
    /**
     * Test attribute "revision"
     */
    public function testPropertyRevision()
    {
        $this->CallResult->setRevision(12345);
        $this->assertEquals(12345, $this->CallResult->getRevision());
        $this->assertIsInt($this->CallResult->getRevision());
    }
    /**
     * Test attribute "call_id"
     */
    public function testPropertyCallId()
    {
        $this->CallResult->setCallId('TEST_STRING');
        $this->assertEquals('TEST_STRING', $this->CallResult->getCallId());
        $this->assertIsString($this->CallResult->getCallId());
        

    }
    /**
     * Test attribute "parent_call_id"
     */
    public function testPropertyParentCallId()
    {
        $this->CallResult->setParentCallId('TEST_STRING');
        $this->assertEquals('TEST_STRING', $this->CallResult->getParentCallId());
        $this->assertIsString($this->CallResult->getParentCallId());
        

    }
    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
        $this->CallResult->setAccountId('TEST_STRING');
        $this->assertEquals('TEST_STRING', $this->CallResult->getAccountId());
        $this->assertIsString($this->CallResult->getAccountId());
        

    }
    /**
     * Test attribute "from"
     */
    public function testPropertyFrom()
    {
        $this->CallResult->setFrom('TEST_STRING');
        $this->assertEquals('TEST_STRING', $this->CallResult->getFrom());
        $this->assertIsString($this->CallResult->getFrom());
        

    }
    /**
     * Test attribute "to"
     */
    public function testPropertyTo()
    {
        $this->CallResult->setTo('TEST_STRING');
        $this->assertEquals('TEST_STRING', $this->CallResult->getTo());
        $this->assertIsString($this->CallResult->getTo());
        

    }
    /**
     * Test attribute "phone_number_id"
     */
    public function testPropertyPhoneNumberId()
    {
        $this->CallResult->setPhoneNumberId('TEST_STRING');
        $this->assertEquals('TEST_STRING', $this->CallResult->getPhoneNumberId());
        $this->assertIsString($this->CallResult->getPhoneNumberId());
        

    }
    /**
     * Test attribute "call_status"
     */
    public function testPropertyCallStatus()
    {
        $this->CallResult->setCallStatus(\FreeClimb\Api\Model\CallStatus::QUEUED);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::QUEUED, $this->CallResult->getCallStatus());
        $this->CallResult->setCallStatus(\FreeClimb\Api\Model\CallStatus::RINGING);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::RINGING, $this->CallResult->getCallStatus());
        $this->CallResult->setCallStatus(\FreeClimb\Api\Model\CallStatus::IN_PROGRESS);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::IN_PROGRESS, $this->CallResult->getCallStatus());
        $this->CallResult->setCallStatus(\FreeClimb\Api\Model\CallStatus::CANCELED);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::CANCELED, $this->CallResult->getCallStatus());
        $this->CallResult->setCallStatus(\FreeClimb\Api\Model\CallStatus::COMPLETED);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::COMPLETED, $this->CallResult->getCallStatus());
        $this->CallResult->setCallStatus(\FreeClimb\Api\Model\CallStatus::FAILED);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::FAILED, $this->CallResult->getCallStatus());
        $this->CallResult->setCallStatus(\FreeClimb\Api\Model\CallStatus::BUSY);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::BUSY, $this->CallResult->getCallStatus());
        $this->CallResult->setCallStatus(\FreeClimb\Api\Model\CallStatus::NO_ANSWER);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::NO_ANSWER, $this->CallResult->getCallStatus());
    }
    /**
     * Test attribute "start_time"
     */
    public function testPropertyStartTime()
    {
        $this->CallResult->setStartTime('TEST_STRING');
        $this->assertEquals('TEST_STRING', $this->CallResult->getStartTime());
        $this->assertIsString($this->CallResult->getStartTime());
        

    }
    /**
     * Test attribute "connect_time"
     */
    public function testPropertyConnectTime()
    {
        $this->CallResult->setConnectTime('TEST_STRING');
        $this->assertEquals('TEST_STRING', $this->CallResult->getConnectTime());
        $this->assertIsString($this->CallResult->getConnectTime());
        

    }
    /**
     * Test attribute "end_time"
     */
    public function testPropertyEndTime()
    {
        $this->CallResult->setEndTime('TEST_STRING');
        $this->assertEquals('TEST_STRING', $this->CallResult->getEndTime());
        $this->assertIsString($this->CallResult->getEndTime());
        

    }
    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
        $this->CallResult->setDuration(12345);
        $this->assertEquals(12345, $this->CallResult->getDuration());
        $this->assertIsInt($this->CallResult->getDuration());
    }
    /**
     * Test attribute "connect_duration"
     */
    public function testPropertyConnectDuration()
    {
        $this->CallResult->setConnectDuration(12345);
        $this->assertEquals(12345, $this->CallResult->getConnectDuration());
        $this->assertIsInt($this->CallResult->getConnectDuration());
    }
    /**
     * Test attribute "direction"
     */
    public function testPropertyDirection()
    {
        $this->CallResult->setDirection(\FreeClimb\Api\Model\CallDirection::INBOUND);
        $this->assertEquals(\FreeClimb\Api\Model\CallDirection::INBOUND, $this->CallResult->getDirection());
        $this->CallResult->setDirection(\FreeClimb\Api\Model\CallDirection::OUTBOUND_API);
        $this->assertEquals(\FreeClimb\Api\Model\CallDirection::OUTBOUND_API, $this->CallResult->getDirection());
        $this->CallResult->setDirection(\FreeClimb\Api\Model\CallDirection::OUTBOUND_DIAL);
        $this->assertEquals(\FreeClimb\Api\Model\CallDirection::OUTBOUND_DIAL, $this->CallResult->getDirection());
    }
    /**
     * Test attribute "answered_by"
     */
    public function testPropertyAnsweredBy()
    {
        $this->CallResult->setAnsweredBy(\FreeClimb\Api\Model\AnsweredBy::HUMAN);
        $this->assertEquals(\FreeClimb\Api\Model\AnsweredBy::HUMAN, $this->CallResult->getAnsweredBy());
        $this->CallResult->setAnsweredBy(\FreeClimb\Api\Model\AnsweredBy::MACHINE);
        $this->assertEquals(\FreeClimb\Api\Model\AnsweredBy::MACHINE, $this->CallResult->getAnsweredBy());
    }
    /**
     * Test attribute "subresource_uris"
     */
    public function testPropertySubresourceUris()
    {
        $this->CallResult->setSubresourceUris(new \stdClass);
        $this->assertInstanceOf(\stdClass::class, $this->CallResult->getSubresourceUris());
    }

    /**
* Test attribute "CallResult"
*/
public function toStringTypeTest() {
    $test1 = new CallResult();    
      $test1->setUri("TS");
      $test1->setDateCreated("TS");
      $test1->setDateUpdated("TS");
      $test1->setRevision(1);
      $test1->setCallId("TS");
      $test1->setParentCallId("TS");
      $test1->setAccountId("TS");
      $test1->setFrom("TS");
      $test1->setTo("TS");
      $test1->setPhoneNumberId("TS");
      $test1->setCallStatus(\FreeClimb\Api\Model\CallStatus::QUEUED);
      $test1->setStartTime("TS");
      $test1->setConnectTime("TS");
      $test1->setEndTime("TS");
      $test1->setDuration(1);
      $test1->setConnectDuration(1);
      $test1->setDirection(\FreeClimb\Api\Model\CallDirection::INBOUND);
      $test1->setAnsweredBy(\FreeClimb\Api\Model\AnsweredBy::HUMAN);
      $testObject = new stdClass(); 
      $test1->setSubresourceUris($testObject);

    $toString1 = $test1->__toString();
    assert(is_string($toString1));
}

/**
 * Test attribute "CallResult"
 */
public function toHeaderValueTest()
{
    $test1 = new CallResult();
      $test1->setUri("TS");
      $test1->setDateCreated("TS");
      $test1->setDateUpdated("TS");
      $test1->setRevision(1);
      $test1->setCallId("TS");
      $test1->setParentCallId("TS");
      $test1->setAccountId("TS");
      $test1->setFrom("TS");
      $test1->setTo("TS");
      $test1->setPhoneNumberId("TS");
      $test1->setCallStatus(\FreeClimb\Api\Model\CallStatus::QUEUED);
      $test1->setStartTime("TS");
      $test1->setConnectTime("TS");
      $test1->setEndTime("TS");
      $test1->setDuration(1);
      $test1->setConnectDuration(1);
      $test1->setDirection(\FreeClimb\Api\Model\CallDirection::INBOUND);
      $test1->setAnsweredBy(\FreeClimb\Api\Model\AnsweredBy::HUMAN);
      $testObject = new stdClass();
      $test1->setSubresourceUris($testObject);

    $toHeaderValue1 = $test1->toHeaderValue();
    assert(is_string($toHeaderValue1));
}


}
