<?php

/**
 * CallStatusWebhookTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto-generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb\Api\Test\Model;

use FreeClimb\Api\Model\CallStatusWebhook;
use PHPUnit\Framework\TestCase;

/**
 * CallStatusWebhookTest Class Doc Comment
 *
 * @category    Class
 * @description A Call has ended and the statusCallbackUrl is being invoked. This is a notification only; All PerCL commands will be ignored.
 * @package     FreeClimb\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CallStatusWebhookTest extends TestCase
{
    protected $CallStatusWebhook;

    /**
     * Test "CallStatusWebhook"
     */
    public function setUp() : void
    {
        $this->CallStatusWebhook = new CallStatusWebhook();
    }
    /**
     * Test attribute "request_type"
     */
    public function testPropertyrequestType()
    {
        $this->CallStatusWebhook->setRequestType('TS');
        $this->assertEquals('TS', $this->CallStatusWebhook->getRequestType());
        $this->assertIsString($this->CallStatusWebhook->getRequestType());
    }
    /**
     * Test attribute "call_id"
     */
    public function testPropertycallId()
    {
        $this->CallStatusWebhook->setCallId('TS');
        $this->assertEquals('TS', $this->CallStatusWebhook->getCallId());
        $this->assertIsString($this->CallStatusWebhook->getCallId());
    }
    /**
     * Test attribute "account_id"
     */
    public function testPropertyaccountId()
    {
        $this->CallStatusWebhook->setAccountId('TS');
        $this->assertEquals('TS', $this->CallStatusWebhook->getAccountId());
        $this->assertIsString($this->CallStatusWebhook->getAccountId());
    }
    /**
     * Test attribute "from"
     */
    public function testPropertyfrom()
    {
        $this->CallStatusWebhook->setFrom('TS');
        $this->assertEquals('TS', $this->CallStatusWebhook->getFrom());
        $this->assertIsString($this->CallStatusWebhook->getFrom());
    }
    /**
     * Test attribute "to"
     */
    public function testPropertyto()
    {
        $this->CallStatusWebhook->setTo('TS');
        $this->assertEquals('TS', $this->CallStatusWebhook->getTo());
        $this->assertIsString($this->CallStatusWebhook->getTo());
    }
    /**
     * Test attribute "call_status"
     */
    public function testPropertycallStatus()
    {
        $this->CallStatusWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::QUEUED);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::QUEUED, $this->CallStatusWebhook->getcallStatus());
        $this->CallStatusWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::RINGING);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::RINGING, $this->CallStatusWebhook->getcallStatus());
        $this->CallStatusWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::IN_PROGRESS);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::IN_PROGRESS, $this->CallStatusWebhook->getcallStatus());
        $this->CallStatusWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::CANCELED);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::CANCELED, $this->CallStatusWebhook->getcallStatus());
        $this->CallStatusWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::COMPLETED);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::COMPLETED, $this->CallStatusWebhook->getcallStatus());
        $this->CallStatusWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::FAILED);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::FAILED, $this->CallStatusWebhook->getcallStatus());
        $this->CallStatusWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::BUSY);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::BUSY, $this->CallStatusWebhook->getcallStatus());
        $this->CallStatusWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::NO_ANSWER);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::NO_ANSWER, $this->CallStatusWebhook->getcallStatus());
    }
    /**
     * Test attribute "call_ended_reason"
     */
    public function testPropertycallEndedReason()
    {
        $this->CallStatusWebhook->setcallEndedReason(\FreeClimb\Api\Model\CallEndedReason::BUSY);
        $this->assertEquals(\FreeClimb\Api\Model\CallEndedReason::BUSY, $this->CallStatusWebhook->getcallEndedReason());
        $this->CallStatusWebhook->setcallEndedReason(\FreeClimb\Api\Model\CallEndedReason::FAILED);
        $this->assertEquals(\FreeClimb\Api\Model\CallEndedReason::FAILED, $this->CallStatusWebhook->getcallEndedReason());
        $this->CallStatusWebhook->setcallEndedReason(\FreeClimb\Api\Model\CallEndedReason::NO_ANSWER);
        $this->assertEquals(\FreeClimb\Api\Model\CallEndedReason::NO_ANSWER, $this->CallStatusWebhook->getcallEndedReason());
        $this->CallStatusWebhook->setcallEndedReason(\FreeClimb\Api\Model\CallEndedReason::CALL_CANCELED);
        $this->assertEquals(\FreeClimb\Api\Model\CallEndedReason::CALL_CANCELED, $this->CallStatusWebhook->getcallEndedReason());
        $this->CallStatusWebhook->setcallEndedReason(\FreeClimb\Api\Model\CallEndedReason::FAR_END_HANGUP);
        $this->assertEquals(\FreeClimb\Api\Model\CallEndedReason::FAR_END_HANGUP, $this->CallStatusWebhook->getcallEndedReason());
        $this->CallStatusWebhook->setcallEndedReason(\FreeClimb\Api\Model\CallEndedReason::APP_HANGUP);
        $this->assertEquals(\FreeClimb\Api\Model\CallEndedReason::APP_HANGUP, $this->CallStatusWebhook->getcallEndedReason());
        $this->CallStatusWebhook->setcallEndedReason(\FreeClimb\Api\Model\CallEndedReason::APP_REJECT);
        $this->assertEquals(\FreeClimb\Api\Model\CallEndedReason::APP_REJECT, $this->CallStatusWebhook->getcallEndedReason());
        $this->CallStatusWebhook->setcallEndedReason(\FreeClimb\Api\Model\CallEndedReason::APP_NO_PERCL);
        $this->assertEquals(\FreeClimb\Api\Model\CallEndedReason::APP_NO_PERCL, $this->CallStatusWebhook->getcallEndedReason());
        $this->CallStatusWebhook->setcallEndedReason(\FreeClimb\Api\Model\CallEndedReason::APP_INVALID_PERCL);
        $this->assertEquals(\FreeClimb\Api\Model\CallEndedReason::APP_INVALID_PERCL, $this->CallStatusWebhook->getcallEndedReason());
        $this->CallStatusWebhook->setcallEndedReason(\FreeClimb\Api\Model\CallEndedReason::CONFERENCE_TERMINATED);
        $this->assertEquals(\FreeClimb\Api\Model\CallEndedReason::CONFERENCE_TERMINATED, $this->CallStatusWebhook->getcallEndedReason());
        $this->CallStatusWebhook->setcallEndedReason(\FreeClimb\Api\Model\CallEndedReason::CONFERENCE_EMPTIED);
        $this->assertEquals(\FreeClimb\Api\Model\CallEndedReason::CONFERENCE_EMPTIED, $this->CallStatusWebhook->getcallEndedReason());
        $this->CallStatusWebhook->setcallEndedReason(\FreeClimb\Api\Model\CallEndedReason::REMOVED_FROM_CONFERENCE);
        $this->assertEquals(\FreeClimb\Api\Model\CallEndedReason::REMOVED_FROM_CONFERENCE, $this->CallStatusWebhook->getcallEndedReason());
        $this->CallStatusWebhook->setcallEndedReason(\FreeClimb\Api\Model\CallEndedReason::MACHINE_DETECTED);
        $this->assertEquals(\FreeClimb\Api\Model\CallEndedReason::MACHINE_DETECTED, $this->CallStatusWebhook->getcallEndedReason());
        $this->CallStatusWebhook->setcallEndedReason(\FreeClimb\Api\Model\CallEndedReason::WEBHOOK_FAILED);
        $this->assertEquals(\FreeClimb\Api\Model\CallEndedReason::WEBHOOK_FAILED, $this->CallStatusWebhook->getcallEndedReason());
        $this->CallStatusWebhook->setcallEndedReason(\FreeClimb\Api\Model\CallEndedReason::WEBHOOK_INVALID_RESPONSE);
        $this->assertEquals(\FreeClimb\Api\Model\CallEndedReason::WEBHOOK_INVALID_RESPONSE, $this->CallStatusWebhook->getcallEndedReason());
        $this->CallStatusWebhook->setcallEndedReason(\FreeClimb\Api\Model\CallEndedReason::VOICE_DISABLED);
        $this->assertEquals(\FreeClimb\Api\Model\CallEndedReason::VOICE_DISABLED, $this->CallStatusWebhook->getcallEndedReason());
        $this->CallStatusWebhook->setcallEndedReason(\FreeClimb\Api\Model\CallEndedReason::CONFIG_ERROR_NO_APPLICATION);
        $this->assertEquals(\FreeClimb\Api\Model\CallEndedReason::CONFIG_ERROR_NO_APPLICATION, $this->CallStatusWebhook->getcallEndedReason());
        $this->CallStatusWebhook->setcallEndedReason(\FreeClimb\Api\Model\CallEndedReason::CONFIG_ERROR_NO_VOICE_URL);
        $this->assertEquals(\FreeClimb\Api\Model\CallEndedReason::CONFIG_ERROR_NO_VOICE_URL, $this->CallStatusWebhook->getcallEndedReason());
        $this->CallStatusWebhook->setcallEndedReason(\FreeClimb\Api\Model\CallEndedReason::MAX_REDIRECTS_ERROR);
        $this->assertEquals(\FreeClimb\Api\Model\CallEndedReason::MAX_REDIRECTS_ERROR, $this->CallStatusWebhook->getcallEndedReason());
        $this->CallStatusWebhook->setcallEndedReason(\FreeClimb\Api\Model\CallEndedReason::PERCL_PROCESSING_ERROR);
        $this->assertEquals(\FreeClimb\Api\Model\CallEndedReason::PERCL_PROCESSING_ERROR, $this->CallStatusWebhook->getcallEndedReason());
        $this->CallStatusWebhook->setcallEndedReason(\FreeClimb\Api\Model\CallEndedReason::INTERNAL_ERROR);
        $this->assertEquals(\FreeClimb\Api\Model\CallEndedReason::INTERNAL_ERROR, $this->CallStatusWebhook->getcallEndedReason());
        $this->CallStatusWebhook->setcallEndedReason(\FreeClimb\Api\Model\CallEndedReason::GRPC_HANGUP);
        $this->assertEquals(\FreeClimb\Api\Model\CallEndedReason::GRPC_HANGUP, $this->CallStatusWebhook->getcallEndedReason());
        $this->CallStatusWebhook->setcallEndedReason(\FreeClimb\Api\Model\CallEndedReason::MAX_DURATION);
        $this->assertEquals(\FreeClimb\Api\Model\CallEndedReason::MAX_DURATION, $this->CallStatusWebhook->getcallEndedReason());
    }
    /**
     * Test attribute "direction"
     */
    public function testPropertydirection()
    {
        $this->CallStatusWebhook->setdirection(\FreeClimb\Api\Model\CallDirection::INBOUND);
        $this->assertEquals(\FreeClimb\Api\Model\CallDirection::INBOUND, $this->CallStatusWebhook->getdirection());
        $this->CallStatusWebhook->setdirection(\FreeClimb\Api\Model\CallDirection::OUTBOUND_API);
        $this->assertEquals(\FreeClimb\Api\Model\CallDirection::OUTBOUND_API, $this->CallStatusWebhook->getdirection());
        $this->CallStatusWebhook->setdirection(\FreeClimb\Api\Model\CallDirection::OUTBOUND_DIAL);
        $this->assertEquals(\FreeClimb\Api\Model\CallDirection::OUTBOUND_DIAL, $this->CallStatusWebhook->getdirection());
    }
    /**
     * Test attribute "conference_id"
     */
    public function testPropertyconferenceId()
    {
        $this->CallStatusWebhook->setConferenceId('TS');
        $this->assertEquals('TS', $this->CallStatusWebhook->getConferenceId());
        $this->assertIsString($this->CallStatusWebhook->getConferenceId());
    }
    /**
     * Test attribute "queue_id"
     */
    public function testPropertyqueueId()
    {
        $this->CallStatusWebhook->setQueueId('TS');
        $this->assertEquals('TS', $this->CallStatusWebhook->getQueueId());
        $this->assertIsString($this->CallStatusWebhook->getQueueId());
    }

    /**
* Test method toStringTest
*/
public function toStringTest() {
    $test1 = new CallStatusWebhook();    
    $test1->setRequestType("TS");
    $test1->setCallId("TS");
    $test1->setAccountId("TS");
    $test1->setFrom("TS");
    $test1->setTo("TS");
    $test1->setCallStatus(\FreeClimb\Api\Model\CallStatus::QUEUED);
    $test1->setCallEndedReason(\FreeClimb\Api\Model\CallEndedReason::BUSY);
    $test1->setDirection(\FreeClimb\Api\Model\CallDirection::INBOUND);
    $test1->setConferenceId("TS");
    $test1->setQueueId("TS");

    $toString1 = $test1->__toString();
    assert(is_string($toString1));
}

/**
 * Test method toHeaderValue
 */
public function toHeaderValueTest()
{
    $test1 = new CallStatusWebhook();
    $test1->setRequestType("TS");
    $test1->setCallId("TS");
    $test1->setAccountId("TS");
    $test1->setFrom("TS");
    $test1->setTo("TS");
    $test1->setCallStatus(\FreeClimb\Api\Model\CallStatus::QUEUED);
    $test1->setCallEndedReason(\FreeClimb\Api\Model\CallEndedReason::BUSY);
    $test1->setDirection(\FreeClimb\Api\Model\CallDirection::INBOUND);
    $test1->setConferenceId("TS");
    $test1->setQueueId("TS");

    $toHeaderValue1 = $test1->toHeaderValue();
    assert(is_string($toHeaderValue1));
}


}
