<?php

/**
 * ConferenceStatusWebhookTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb\Api\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ConferenceStatusWebhookTest Class Doc Comment
 *
 * @category    Class
 * @description The context or reason why this request is being made. Will be conferenceStatus - A Conference&#39;s status changed and its statusCallbackUrl is being invoked.
 * @package     FreeClimb\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
#[\AllowDynamicProperties]
class ConferenceStatusWebhookTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $this->ConferenceStatusWebhook = new \FreeClimb\Api\Model\ConferenceStatusWebhook();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }


    public function testPropertyRequestType()
    {

        $this->ConferenceStatusWebhook->setRequestType('TS');
        $this->assertEquals('TS', $this->ConferenceStatusWebhook->getRequestType());
        $this->assertIsString($this->ConferenceStatusWebhook->getRequestType());
    }

    public function testPropertyCallId()
    {

        $this->ConferenceStatusWebhook->setCallId('TS');
        $this->assertEquals('TS', $this->ConferenceStatusWebhook->getCallId());
        $this->assertIsString($this->ConferenceStatusWebhook->getCallId());
    }

    public function testPropertyAccountId()
    {

        $this->ConferenceStatusWebhook->setAccountId('TS');
        $this->assertEquals('TS', $this->ConferenceStatusWebhook->getAccountId());
        $this->assertIsString($this->ConferenceStatusWebhook->getAccountId());
    }

    public function testPropertyFrom()
    {

        $this->ConferenceStatusWebhook->setFrom('TS');
        $this->assertEquals('TS', $this->ConferenceStatusWebhook->getFrom());
        $this->assertIsString($this->ConferenceStatusWebhook->getFrom());
    }

    public function testPropertyTo()
    {

        $this->ConferenceStatusWebhook->setTo('TS');
        $this->assertEquals('TS', $this->ConferenceStatusWebhook->getTo());
        $this->assertIsString($this->ConferenceStatusWebhook->getTo());
    }

    public function testPropertyCallStatus()
    {
        $this->ConferenceStatusWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::QUEUED);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::QUEUED, $this->ConferenceStatusWebhook->getcallStatus());
        $this->ConferenceStatusWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::RINGING);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::RINGING, $this->ConferenceStatusWebhook->getcallStatus());
        $this->ConferenceStatusWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::IN_PROGRESS);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::IN_PROGRESS, $this->ConferenceStatusWebhook->getcallStatus());
        $this->ConferenceStatusWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::CANCELED);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::CANCELED, $this->ConferenceStatusWebhook->getcallStatus());
        $this->ConferenceStatusWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::COMPLETED);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::COMPLETED, $this->ConferenceStatusWebhook->getcallStatus());
        $this->ConferenceStatusWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::FAILED);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::FAILED, $this->ConferenceStatusWebhook->getcallStatus());
        $this->ConferenceStatusWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::BUSY);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::BUSY, $this->ConferenceStatusWebhook->getcallStatus());
        $this->ConferenceStatusWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::NO_ANSWER);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::NO_ANSWER, $this->ConferenceStatusWebhook->getcallStatus());
    }

    public function testPropertyDirection()
    {
        $this->ConferenceStatusWebhook->setdirection(\FreeClimb\Api\Model\CallDirection::INBOUND);
        $this->assertEquals(\FreeClimb\Api\Model\CallDirection::INBOUND, $this->ConferenceStatusWebhook->getdirection());
        $this->ConferenceStatusWebhook->setdirection(\FreeClimb\Api\Model\CallDirection::OUTBOUND_API);
        $this->assertEquals(\FreeClimb\Api\Model\CallDirection::OUTBOUND_API, $this->ConferenceStatusWebhook->getdirection());
        $this->ConferenceStatusWebhook->setdirection(\FreeClimb\Api\Model\CallDirection::OUTBOUND_DIAL);
        $this->assertEquals(\FreeClimb\Api\Model\CallDirection::OUTBOUND_DIAL, $this->ConferenceStatusWebhook->getdirection());
    }

    public function testPropertyConferenceId()
    {

        $this->ConferenceStatusWebhook->setConferenceId('TS');
        $this->assertEquals('TS', $this->ConferenceStatusWebhook->getConferenceId());
        $this->assertIsString($this->ConferenceStatusWebhook->getConferenceId());
    }

    public function testPropertyQueueId()
    {

        $this->ConferenceStatusWebhook->setQueueId('TS');
        $this->assertEquals('TS', $this->ConferenceStatusWebhook->getQueueId());
        $this->assertIsString($this->ConferenceStatusWebhook->getQueueId());
    }

    public function testPropertyStatus()
    {
        $this->ConferenceStatusWebhook->setstatus(\FreeClimb\Api\Model\ConferenceStatus::EMPTY);
        $this->assertEquals(\FreeClimb\Api\Model\ConferenceStatus::EMPTY, $this->ConferenceStatusWebhook->getstatus());
        $this->ConferenceStatusWebhook->setstatus(\FreeClimb\Api\Model\ConferenceStatus::POPULATED);
        $this->assertEquals(\FreeClimb\Api\Model\ConferenceStatus::POPULATED, $this->ConferenceStatusWebhook->getstatus());
        $this->ConferenceStatusWebhook->setstatus(\FreeClimb\Api\Model\ConferenceStatus::IN_PROGRESS);
        $this->assertEquals(\FreeClimb\Api\Model\ConferenceStatus::IN_PROGRESS, $this->ConferenceStatusWebhook->getstatus());
        $this->ConferenceStatusWebhook->setstatus(\FreeClimb\Api\Model\ConferenceStatus::TERMINATED);
        $this->assertEquals(\FreeClimb\Api\Model\ConferenceStatus::TERMINATED, $this->ConferenceStatusWebhook->getstatus());
    }

    public function testPropertyRecordingUrl()
    {

        $this->ConferenceStatusWebhook->setRecordingUrl('TS');
        $this->assertEquals('TS', $this->ConferenceStatusWebhook->getRecordingUrl());
        $this->assertIsString($this->ConferenceStatusWebhook->getRecordingUrl());
    }

    public function testPropertyRecordingId()
    {

        $this->ConferenceStatusWebhook->setRecordingId('TS');
        $this->assertEquals('TS', $this->ConferenceStatusWebhook->getRecordingId());
        $this->assertIsString($this->ConferenceStatusWebhook->getRecordingId());
    }

    public function testPropertyRecordingDurationSec()
    {


        $this->ConferenceStatusWebhook->setrecordingDurationSec(1);
        $this->assertEquals(1, $this->ConferenceStatusWebhook->getrecordingDurationSec());
        $this->assertIsNumeric($this->ConferenceStatusWebhook->getrecordingDurationSec());

    }
    /**
     * Test attribute "ConferenceStatusWebhook::deserialize"
     */
    public function testDeserializeConferenceStatusWebhook()
    {
        $json = "{\"requestType\":\"conferenceStatus\"}";
        $this->assertInstanceOf(\FreeClimb\Api\Model\ConferenceStatusWebhook::class, \FreeClimb\Api\Model\ConferenceStatusWebhook::deserialize($json));
    }
}
