<?php

/**
 * ExportListTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb\Api\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ExportListTest Class Doc Comment
 *
 * @category    Class
 * @description ExportList
 * @package     FreeClimb\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
#[\AllowDynamicProperties]
class ExportListTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $this->ExportList = new \FreeClimb\Api\Model\ExportList();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }


    public function testPropertyTotal()
    {


        $this->ExportList->settotal(1);
        $this->assertEquals(1, $this->ExportList->gettotal());
        $this->assertIsNumeric($this->ExportList->gettotal());

    }

    public function testPropertyStart()
    {


        $this->ExportList->setstart(1);
        $this->assertEquals(1, $this->ExportList->getstart());
        $this->assertIsNumeric($this->ExportList->getstart());

    }

    public function testPropertyEnd()
    {


        $this->ExportList->setend(1);
        $this->assertEquals(1, $this->ExportList->getend());
        $this->assertIsNumeric($this->ExportList->getend());

    }

    public function testPropertyPage()
    {


        $this->ExportList->setpage(1);
        $this->assertEquals(1, $this->ExportList->getpage());
        $this->assertIsNumeric($this->ExportList->getpage());

    }

    public function testPropertyNumPages()
    {


        $this->ExportList->setnumPages(1);
        $this->assertEquals(1, $this->ExportList->getnumPages());
        $this->assertIsNumeric($this->ExportList->getnumPages());

    }

    public function testPropertyPageSize()
    {


        $this->ExportList->setpageSize(1);
        $this->assertEquals(1, $this->ExportList->getpageSize());
        $this->assertIsNumeric($this->ExportList->getpageSize());

    }

    public function testPropertyNextPageUri()
    {

        $this->ExportList->setNextPageUri('TS');
        $this->assertEquals('TS', $this->ExportList->getNextPageUri());
        $this->assertIsString($this->ExportList->getNextPageUri());
    }

    public function testPropertyExports()
    {
        $this->ExportList->setexports([]);
        $this->assertEquals([], $this->ExportList->getexports());
        $this->assertIsArray($this->ExportList->getexports());
    }
}
