<?php

/**
 * GetDigitsTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto-generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb\Api\Test\Model;

use FreeClimb\Api\Model\GetDigits;
use PHPUnit\Framework\TestCase;

/**
 * GetDigitsTest Class Doc Comment
 *
 * @category    Class
 * @description The &#x60;GetDigits&#x60; command collects DTMF inputs from the caller. It is only supported only when there is a single party on the Call. &#x60;GetDigits&#x60; is a Terminal Command — any actions following it are never executed. When the Caller is done entering the digits, FreeClimb submits that data to the provided &#x60;actionUrl&#x60; using an HTTP POST request. Your server will be required to respond to the FreeClimb Webhook with PerCL to continue handling the call.
 * @package     FreeClimb\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GetDigitsTest extends TestCase
{
    protected $GetDigits;

    /**
     * Test "GetDigits"
     */
    public function setUp() : void
    {
        $this->GetDigits = new GetDigits();
    }
    /**
     * Test attribute "action_url"
     */
    public function testPropertyActionUrl()
    {
        $this->GetDigits->setActionUrl('TEST_STRING');
        $this->assertEquals('TEST_STRING', $this->GetDigits->getActionUrl());
        $this->assertIsString($this->GetDigits->getActionUrl());
        

    }
    /**
     * Test attribute "digit_timeout_ms"
     */
    public function testPropertyDigitTimeoutMs()
    {
        $this->GetDigits->setDigitTimeoutMs(12345);
        $this->assertEquals(12345, $this->GetDigits->getDigitTimeoutMs());
        $this->assertIsInt($this->GetDigits->getDigitTimeoutMs());
    }
    /**
     * Test attribute "finish_on_key"
     */
    public function testPropertyFinishOnKey()
    {
        $this->GetDigits->setFinishOnKey('TEST_STRING');
        $this->assertEquals('TEST_STRING', $this->GetDigits->getFinishOnKey());
        $this->assertIsString($this->GetDigits->getFinishOnKey());
        

    }
    /**
     * Test attribute "flush_buffer"
     */
    public function testPropertyFlushBuffer()
    {
        $this->GetDigits->setFlushBuffer(true);
        $this->assertTrue($this->GetDigits->getFlushBuffer());
        $this->assertIsBool($this->GetDigits->getFlushBuffer());
    }
    /**
     * Test attribute "initial_timeout_ms"
     */
    public function testPropertyInitialTimeoutMs()
    {
        $this->GetDigits->setInitialTimeoutMs(12345);
        $this->assertEquals(12345, $this->GetDigits->getInitialTimeoutMs());
        $this->assertIsInt($this->GetDigits->getInitialTimeoutMs());
    }
    /**
     * Test attribute "max_digits"
     */
    public function testPropertyMaxDigits()
    {
        $this->GetDigits->setMaxDigits(12345);
        $this->assertEquals(12345, $this->GetDigits->getMaxDigits());
        $this->assertIsInt($this->GetDigits->getMaxDigits());
    }
    /**
     * Test attribute "min_digits"
     */
    public function testPropertyMinDigits()
    {
        $this->GetDigits->setMinDigits(12345);
        $this->assertEquals(12345, $this->GetDigits->getMinDigits());
        $this->assertIsInt($this->GetDigits->getMinDigits());
    }
    /**
     * Test attribute "prompts"
     */
    public function testPropertyPrompts()
    {
        $this->GetDigits->setPrompts([]);
        $this->assertEquals([], $this->GetDigits->getPrompts());
        $this->assertIsArray($this->GetDigits->getPrompts());
    }
    /**
     * Test attribute "privacy_mode"
     */
    public function testPropertyPrivacyMode()
    {
        $this->GetDigits->setPrivacyMode(true);
        $this->assertTrue($this->GetDigits->getPrivacyMode());
        $this->assertIsBool($this->GetDigits->getPrivacyMode());
    }

    /**
* Test method toStringTest
*/
public function toStringTest() {
    $test1 = new GetDigits();    
      try {
          $uri1 = "TEST_STRING";
          $test1->setActionUrl($uri1);
      } catch (Exception $e) {
          echo $e->getMessage();
      }
      $test1->setDigitTimeoutMs(1);
      $test1->setFinishOnKey("TS");
      $test1->setFlushBuffer(true);
      $test1->setInitialTimeoutMs(1);
      $test1->setMaxDigits(1);
      $test1->setMinDigits(1);
      $testList = [];
      $test1->setPrompts($testList);
      $test1->setPrivacyMode(true);

    $toString1 = $test1->__toString();
    assert(is_string($toString1));
}

/**
 * Test method toHeaderValue
 */
public function toHeaderValueTest()
{
    $test1 = new GetDigits();
      try {
          $uri1 = "TEST_STRING";
          $test1->setActionUrl($uri1);
      } catch (Exception $e) {
          echo $e->getMessage();
      }
      $test1->setDigitTimeoutMs(1);
      $test1->setFinishOnKey("TS");
      $test1->setFlushBuffer(true);
      $test1->setInitialTimeoutMs(1);
      $test1->setMaxDigits(1);
      $test1->setMinDigits(1);
      $testList = [];
      $test1->setPrompts($testList);
      $test1->setPrivacyMode(true);

    $toHeaderValue1 = $test1->toHeaderValue();
    assert(is_string($toHeaderValue1));
}


}
