<?php

/**
 * RecordWebhookTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb\Api\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * RecordWebhookTest Class Doc Comment
 *
 * @category    Class
 * @description The RecordUtterance command has completed and its actionUrl is being invoked.
 * @package     FreeClimb\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
#[\AllowDynamicProperties]
class RecordWebhookTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $this->RecordWebhook = new \FreeClimb\Api\Model\RecordWebhook();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test attribute "request_type"
     */
    public function testPropertyRequestType()
    {
        $this->RecordWebhook->setRequestType('TS');
        $this->assertEquals('TS', $this->RecordWebhook->getRequestType());
        $this->assertIsString($this->RecordWebhook->getRequestType());
    }
    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
        $this->RecordWebhook->setAccountId('TS');
        $this->assertEquals('TS', $this->RecordWebhook->getAccountId());
        $this->assertIsString($this->RecordWebhook->getAccountId());
    }
    /**
     * Test attribute "call_id"
     */
    public function testPropertyCallId()
    {
        $this->RecordWebhook->setCallId('TS');
        $this->assertEquals('TS', $this->RecordWebhook->getCallId());
        $this->assertIsString($this->RecordWebhook->getCallId());
    }
    /**
     * Test attribute "from"
     */
    public function testPropertyFrom()
    {
        $this->RecordWebhook->setFrom('TS');
        $this->assertEquals('TS', $this->RecordWebhook->getFrom());
        $this->assertIsString($this->RecordWebhook->getFrom());
    }
    /**
     * Test attribute "to"
     */
    public function testPropertyTo()
    {
        $this->RecordWebhook->setTo('TS');
        $this->assertEquals('TS', $this->RecordWebhook->getTo());
        $this->assertIsString($this->RecordWebhook->getTo());
    }
    /**
     * Test attribute "call_status"
     */
    public function testPropertyCallStatus()
    {
        $this->RecordWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::QUEUED);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::QUEUED, $this->RecordWebhook->getcallStatus());
        $this->RecordWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::RINGING);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::RINGING, $this->RecordWebhook->getcallStatus());
        $this->RecordWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::IN_PROGRESS);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::IN_PROGRESS, $this->RecordWebhook->getcallStatus());
        $this->RecordWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::CANCELED);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::CANCELED, $this->RecordWebhook->getcallStatus());
        $this->RecordWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::COMPLETED);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::COMPLETED, $this->RecordWebhook->getcallStatus());
        $this->RecordWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::FAILED);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::FAILED, $this->RecordWebhook->getcallStatus());
        $this->RecordWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::BUSY);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::BUSY, $this->RecordWebhook->getcallStatus());
        $this->RecordWebhook->setcallStatus(\FreeClimb\Api\Model\CallStatus::NO_ANSWER);
        $this->assertEquals(\FreeClimb\Api\Model\CallStatus::NO_ANSWER, $this->RecordWebhook->getcallStatus());
    }
    /**
     * Test attribute "direction"
     */
    public function testPropertyDirection()
    {
        $this->RecordWebhook->setdirection(\FreeClimb\Api\Model\CallDirection::INBOUND);
        $this->assertEquals(\FreeClimb\Api\Model\CallDirection::INBOUND, $this->RecordWebhook->getdirection());
        $this->RecordWebhook->setdirection(\FreeClimb\Api\Model\CallDirection::OUTBOUND_API);
        $this->assertEquals(\FreeClimb\Api\Model\CallDirection::OUTBOUND_API, $this->RecordWebhook->getdirection());
        $this->RecordWebhook->setdirection(\FreeClimb\Api\Model\CallDirection::OUTBOUND_DIAL);
        $this->assertEquals(\FreeClimb\Api\Model\CallDirection::OUTBOUND_DIAL, $this->RecordWebhook->getdirection());
    }
    /**
     * Test attribute "conference_id"
     */
    public function testPropertyConferenceId()
    {
        $this->RecordWebhook->setConferenceId('TS');
        $this->assertEquals('TS', $this->RecordWebhook->getConferenceId());
        $this->assertIsString($this->RecordWebhook->getConferenceId());
    }
    /**
     * Test attribute "queue_id"
     */
    public function testPropertyQueueId()
    {
        $this->RecordWebhook->setQueueId('TS');
        $this->assertEquals('TS', $this->RecordWebhook->getQueueId());
        $this->assertIsString($this->RecordWebhook->getQueueId());
    }
    /**
     * Test attribute "recording_id"
     */
    public function testPropertyRecordingId()
    {
        $this->RecordWebhook->setRecordingId('TS');
        $this->assertEquals('TS', $this->RecordWebhook->getRecordingId());
        $this->assertIsString($this->RecordWebhook->getRecordingId());
    }
    /**
     * Test attribute "recording_url"
     */
    public function testPropertyRecordingUrl()
    {
        $this->RecordWebhook->setRecordingUrl('TS');
        $this->assertEquals('TS', $this->RecordWebhook->getRecordingUrl());
        $this->assertIsString($this->RecordWebhook->getRecordingUrl());
    }
    /**
     * Test attribute "recording_size"
     */
    public function testPropertyRecordingSize()
    {
        $this->RecordWebhook->setRecordingSize('TS');
        $this->assertEquals('TS', $this->RecordWebhook->getRecordingSize());
        $this->assertIsString($this->RecordWebhook->getRecordingSize());
    }
    /**
     * Test attribute "recording_format"
     */
    public function testPropertyRecordingFormat()
    {
        $this->RecordWebhook->setRecordingFormat('TS');
        $this->assertEquals('TS', $this->RecordWebhook->getRecordingFormat());
        $this->assertIsString($this->RecordWebhook->getRecordingFormat());
    }
    /**
     * Test attribute "recording_duration_sec"
     */
    public function testPropertyRecordingDurationSec()
    {


        $this->RecordWebhook->setrecordingDurationSec(1);
        $this->assertEquals(1, $this->RecordWebhook->getrecordingDurationSec());
        $this->assertIsNumeric($this->RecordWebhook->getrecordingDurationSec());

    }
    /**
     * Test attribute "term_reason"
     */
    public function testPropertyTermReason()
    {
        $this->RecordWebhook->settermReason(\FreeClimb\Api\Model\RecordUtteranceTermReason::FINISH_KEY);
        $this->assertEquals(\FreeClimb\Api\Model\RecordUtteranceTermReason::FINISH_KEY, $this->RecordWebhook->gettermReason());
        $this->RecordWebhook->settermReason(\FreeClimb\Api\Model\RecordUtteranceTermReason::TIMEOUT);
        $this->assertEquals(\FreeClimb\Api\Model\RecordUtteranceTermReason::TIMEOUT, $this->RecordWebhook->gettermReason());
        $this->RecordWebhook->settermReason(\FreeClimb\Api\Model\RecordUtteranceTermReason::HANGUP);
        $this->assertEquals(\FreeClimb\Api\Model\RecordUtteranceTermReason::HANGUP, $this->RecordWebhook->gettermReason());
        $this->RecordWebhook->settermReason(\FreeClimb\Api\Model\RecordUtteranceTermReason::MAX_LENGTH);
        $this->assertEquals(\FreeClimb\Api\Model\RecordUtteranceTermReason::MAX_LENGTH, $this->RecordWebhook->gettermReason());
    }
    /**
     * Test attribute "parent_call_id"
     */
    public function testPropertyParentCallId()
    {
        $this->RecordWebhook->setParentCallId('TS');
        $this->assertEquals('TS', $this->RecordWebhook->getParentCallId());
        $this->assertIsString($this->RecordWebhook->getParentCallId());
    }
    /**
     * Test attribute "privacy_mode"
     */
    public function testPropertyPrivacyMode()
    {
        $this->RecordWebhook->setprivacyMode(false);
        $this->assertFalse($this->RecordWebhook->getprivacyMode());
        $this->assertIsBool($this->RecordWebhook->getprivacyMode());
    }
    /**
     * Test attribute "RecordWebhook::deserialize"
     */
    public function testDeserializeRecordWebhook()
    {
        $json = "{\"requestType\":\"record\"}";
        $this->assertInstanceOf(\FreeClimb\Api\Model\RecordWebhook::class, \FreeClimb\Api\Model\RecordWebhook::deserialize($json));
    }
}
