<?php

/**
 * RecordingListTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb\Api\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * RecordingListTest Class Doc Comment
 *
 * @category    Class
 * @description RecordingList
 * @package     FreeClimb\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
#[\AllowDynamicProperties]
class RecordingListTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
        $this->RecordingList = new \FreeClimb\Api\Model\RecordingList();
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {


        $this->RecordingList->settotal(1);
        $this->assertEquals(1, $this->RecordingList->gettotal());
        $this->assertIsNumeric($this->RecordingList->gettotal());

    }
    /**
     * Test attribute "start"
     */
    public function testPropertyStart()
    {


        $this->RecordingList->setstart(1);
        $this->assertEquals(1, $this->RecordingList->getstart());
        $this->assertIsNumeric($this->RecordingList->getstart());

    }
    /**
     * Test attribute "end"
     */
    public function testPropertyEnd()
    {


        $this->RecordingList->setend(1);
        $this->assertEquals(1, $this->RecordingList->getend());
        $this->assertIsNumeric($this->RecordingList->getend());

    }
    /**
     * Test attribute "page"
     */
    public function testPropertyPage()
    {


        $this->RecordingList->setpage(1);
        $this->assertEquals(1, $this->RecordingList->getpage());
        $this->assertIsNumeric($this->RecordingList->getpage());

    }
    /**
     * Test attribute "num_pages"
     */
    public function testPropertyNumPages()
    {


        $this->RecordingList->setnumPages(1);
        $this->assertEquals(1, $this->RecordingList->getnumPages());
        $this->assertIsNumeric($this->RecordingList->getnumPages());

    }
    /**
     * Test attribute "page_size"
     */
    public function testPropertyPageSize()
    {


        $this->RecordingList->setpageSize(1);
        $this->assertEquals(1, $this->RecordingList->getpageSize());
        $this->assertIsNumeric($this->RecordingList->getpageSize());

    }
    /**
     * Test attribute "next_page_uri"
     */
    public function testPropertyNextPageUri()
    {

        $this->RecordingList->setNextPageUri('TS');
        $this->assertEquals('TS', $this->RecordingList->getNextPageUri());
        $this->assertIsString($this->RecordingList->getNextPageUri());
    }
    /**
     * Test attribute "recordings"
     */
    public function testPropertyRecordings()
    {
        $this->RecordingList->setrecordings([]);
        $this->assertEquals([], $this->RecordingList->getrecordings());
        $this->assertIsArray($this->RecordingList->getrecordings());
    }
}
