<?php
/**
 * SMSTenDLCBrandTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb\Api\Test\Model;

use FreeClimb\Api\Model\SMSTenDLCBrand;
use PHPUnit\Framework\TestCase;

/**
 * SMSTenDLCBrandTest Class Doc Comment
 *
 * @category    Class
 * @description A brand is a business identity behind the campaign.
 * @package     FreeClimb\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SMSTenDLCBrandTest extends TestCase
{
    protected $SMSTenDLCBrand;

    /**
     * Test "SMSTenDLCBrand"
     */
    public function setUp(): void
    {
        $this->SMSTenDLCBrand = new SMSTenDLCBrand();
    }
    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
        $this->SMSTenDLCBrand->setAccountId('TEST_STRING');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getAccountId(), 'TEST_STRING');
        $this->assertIsString($this->SMSTenDLCBrand->getAccountId());


    }
    /**
     * Test attribute "entity_type"
     */
    public function testPropertyEntityType()
    {

        $this->SMSTenDLCBrand->setEntityType('PRIVATE_PROFIT');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getEntityType(), 'PRIVATE_PROFIT');
        $this->assertIsString($this->SMSTenDLCBrand->getEntityType());

    }
    /**
     * Test attribute "csp_id"
     */
    public function testPropertyCspId()
    {
        $this->SMSTenDLCBrand->setCspId('TEST_STRING');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getCspId(), 'TEST_STRING');
        $this->assertIsString($this->SMSTenDLCBrand->getCspId());


    }
    /**
     * Test attribute "brand_id"
     */
    public function testPropertyBrandId()
    {
        $this->SMSTenDLCBrand->setBrandId('TEST_STRING');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getBrandId(), 'TEST_STRING');
        $this->assertIsString($this->SMSTenDLCBrand->getBrandId());


    }
    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
        $this->SMSTenDLCBrand->setFirstName('TEST_STRING');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getFirstName(), 'TEST_STRING');
        $this->assertIsString($this->SMSTenDLCBrand->getFirstName());


    }
    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
        $this->SMSTenDLCBrand->setLastName('TEST_STRING');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getLastName(), 'TEST_STRING');
        $this->assertIsString($this->SMSTenDLCBrand->getLastName());


    }
    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {
        $this->SMSTenDLCBrand->setDisplayName('TEST_STRING');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getDisplayName(), 'TEST_STRING');
        $this->assertIsString($this->SMSTenDLCBrand->getDisplayName());


    }
    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {
        $this->SMSTenDLCBrand->setCompanyName('TEST_STRING');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getCompanyName(), 'TEST_STRING');
        $this->assertIsString($this->SMSTenDLCBrand->getCompanyName());


    }
    /**
     * Test attribute "ein"
     */
    public function testPropertyEin()
    {
        $this->SMSTenDLCBrand->setEin('TEST_STRING');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getEin(), 'TEST_STRING');
        $this->assertIsString($this->SMSTenDLCBrand->getEin());


    }
    /**
     * Test attribute "ein_issuing_country"
     */
    public function testPropertyEinIssuingCountry()
    {
        $this->SMSTenDLCBrand->setEinIssuingCountry('TE');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getEinIssuingCountry(), 'TE');
        $this->assertIsString($this->SMSTenDLCBrand->getEinIssuingCountry());


    }
    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
        $this->SMSTenDLCBrand->setPhone('TEST_STRING');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getPhone(), 'TEST_STRING');
        $this->assertIsString($this->SMSTenDLCBrand->getPhone());


    }
    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
        $this->SMSTenDLCBrand->setStreet('TEST_STRING');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getStreet(), 'TEST_STRING');
        $this->assertIsString($this->SMSTenDLCBrand->getStreet());


    }
    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
        $this->SMSTenDLCBrand->setCity('TEST_STRING');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getCity(), 'TEST_STRING');
        $this->assertIsString($this->SMSTenDLCBrand->getCity());


    }
    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
        $this->SMSTenDLCBrand->setState('TEST_STRING');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getState(), 'TEST_STRING');
        $this->assertIsString($this->SMSTenDLCBrand->getState());


    }
    /**
     * Test attribute "postal_code"
     */
    public function testPropertyPostalCode()
    {
        $this->SMSTenDLCBrand->setPostalCode('TESTSTRING');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getPostalCode(), 'TESTSTRING');
        $this->assertIsString($this->SMSTenDLCBrand->getPostalCode());


    }
    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
        $this->SMSTenDLCBrand->setCountry('TE');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getCountry(), 'TE');
        $this->assertIsString($this->SMSTenDLCBrand->getCountry());


    }
    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
        $this->SMSTenDLCBrand->setEmail('TEST_STRING');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getEmail(), 'TEST_STRING');
        $this->assertIsString($this->SMSTenDLCBrand->getEmail());


    }
    /**
     * Test attribute "stock_symbol"
     */
    public function testPropertyStockSymbol()
    {
        $this->SMSTenDLCBrand->setStockSymbol('TESTSTRING');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getStockSymbol(), 'TESTSTRING');
        $this->assertIsString($this->SMSTenDLCBrand->getStockSymbol());


    }
    /**
     * Test attribute "stock_exchange"
     */
    public function testPropertyStockExchange()
    {

        $this->SMSTenDLCBrand->setStockExchange('NONE');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getStockExchange(), 'NONE');
        $this->assertIsString($this->SMSTenDLCBrand->getStockExchange());

    }
    /**
     * Test attribute "ip_address"
     */
    public function testPropertyIpAddress()
    {
        $this->SMSTenDLCBrand->setIpAddress('TEST_STRING');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getIpAddress(), 'TEST_STRING');
        $this->assertIsString($this->SMSTenDLCBrand->getIpAddress());


    }
    /**
     * Test attribute "website"
     */
    public function testPropertyWebsite()
    {
        $this->SMSTenDLCBrand->setWebsite('TEST_STRING');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getWebsite(), 'TEST_STRING');
        $this->assertIsString($this->SMSTenDLCBrand->getWebsite());


    }
    /**
     * Test attribute "brand_relationship"
     */
    public function testPropertyBrandRelationship()
    {

        $this->SMSTenDLCBrand->setBrandRelationship('BASIC_ACCOUNT');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getBrandRelationship(), 'BASIC_ACCOUNT');
        $this->assertIsString($this->SMSTenDLCBrand->getBrandRelationship());

    }
    /**
     * Test attribute "vertical"
     */
    public function testPropertyVertical()
    {
        $this->SMSTenDLCBrand->setVertical('TEST_STRING');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getVertical(), 'TEST_STRING');
        $this->assertIsString($this->SMSTenDLCBrand->getVertical());


    }
    /**
     * Test attribute "alt_business_id"
     */
    public function testPropertyAltBusinessId()
    {
        $this->SMSTenDLCBrand->setAltBusinessId('TEST_STRING');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getAltBusinessId(), 'TEST_STRING');
        $this->assertIsString($this->SMSTenDLCBrand->getAltBusinessId());


    }
    /**
     * Test attribute "alt_business_id_type"
     */
    public function testPropertyAltBusinessIdType()
    {

        $this->SMSTenDLCBrand->setAltBusinessIdType('NONE');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getAltBusinessIdType(), 'NONE');
        $this->assertIsString($this->SMSTenDLCBrand->getAltBusinessIdType());

    }
    /**
     * Test attribute "universal_ein"
     */
    public function testPropertyUniversalEin()
    {
        $this->SMSTenDLCBrand->setUniversalEin('TEST_STRING');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getUniversalEin(), 'TEST_STRING');
        $this->assertIsString($this->SMSTenDLCBrand->getUniversalEin());


    }
    /**
     * Test attribute "reference_id"
     */
    public function testPropertyReferenceId()
    {
        $this->SMSTenDLCBrand->setReferenceId('TEST_STRING');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getReferenceId(), 'TEST_STRING');
        $this->assertIsString($this->SMSTenDLCBrand->getReferenceId());


    }
    /**
     * Test attribute "optional_attributes"
     */
    public function testPropertyOptionalAttributes()
    {
        $this->SMSTenDLCBrand->setOptionalAttributes(new \stdClass);
        $this->assertIsObject($this->SMSTenDLCBrand->getOptionalAttributes());
    }
    /**
     * Test attribute "mock"
     */
    public function testPropertyMock()
    {
        $this->SMSTenDLCBrand->setMock(true);
        $this->assertEquals($this->SMSTenDLCBrand->getMock(), true);
        $this->assertIsBool($this->SMSTenDLCBrand->getMock());
    }
    /**
     * Test attribute "identity_status"
     */
    public function testPropertyIdentityStatus()
    {

        $this->SMSTenDLCBrand->setIdentityStatus('SELF_DECLARED');
        $this->assertStringContainsString($this->SMSTenDLCBrand->getIdentityStatus(), 'SELF_DECLARED');
        $this->assertIsString($this->SMSTenDLCBrand->getIdentityStatus());

    }
    /**
     * Test attribute "create_date"
     */
    public function testPropertyCreateDate()
    {
    }
}