<?php

/**
 * SMSTenDLCBrandRelationshipTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto-generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb\Api\Test\Model;

use FreeClimb\Api\Model\SMSTenDLCBrandRelationship;
use PHPUnit\Framework\TestCase;

/**
 * SMSTenDLCBrandRelationshipTest Class Doc Comment
 *
 * @category    Class
 * @description Brand relationship to the CSP
 * @package     FreeClimb\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SMSTenDLCBrandRelationshipTest extends TestCase
{
    protected $SMSTenDLCBrandRelationship;

    /**
     * Test "SMSTenDLCBrandRelationship"
     */
    public function setUp() : void
    {
        $this->SMSTenDLCBrandRelationship = new SMSTenDLCBrandRelationship();
    }

public function test_BASIC_ACCOUNT_should_deserialize_to_string() {
    $test = SMSTenDLCBrandRelationship::BASIC_ACCOUNT;
    $this->assertEquals($test, 'BASIC_ACCOUNT');
}


public function test_SMALL_ACCOUNT_should_deserialize_to_string() {
    $test = SMSTenDLCBrandRelationship::SMALL_ACCOUNT;
    $this->assertEquals($test, 'SMALL_ACCOUNT');
}


public function test_MEDIUM_ACCOUNT_should_deserialize_to_string() {
    $test = SMSTenDLCBrandRelationship::MEDIUM_ACCOUNT;
    $this->assertEquals($test, 'MEDIUM_ACCOUNT');
}


public function test_LARGE_ACCOUNT_should_deserialize_to_string() {
    $test = SMSTenDLCBrandRelationship::LARGE_ACCOUNT;
    $this->assertEquals($test, 'LARGE_ACCOUNT');
}


public function test_KEY_ACCOUNT_should_deserialize_to_string() {
    $test = SMSTenDLCBrandRelationship::KEY_ACCOUNT;
    $this->assertEquals($test, 'KEY_ACCOUNT');
}


}
