<?php

/**
 * TranscribeReasonTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto-generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb\Api\Test\Model;

use FreeClimb\Api\Model\TranscribeReason;
use PHPUnit\Framework\TestCase;

/**
 * TranscribeReasonTest Class Doc Comment
 *
 * @category    Class
 * @description TranscribeReason
 * @package     FreeClimb\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TranscribeReasonTest extends TestCase
{
    protected $TranscribeReason;

    /**
     * Test "TranscribeReason"
     */
    public function setUp() : void
    {
        $this->TranscribeReason = new TranscribeReason();
    }

public function test_INTERNAL_ERROR_should_deserialize_to_string() {
    $test = TranscribeReason::INTERNAL_ERROR;
    $this->assertEquals($test, 'internalError');
}


public function test_HANGUP_should_deserialize_to_string() {
    $test = TranscribeReason::HANGUP;
    $this->assertEquals($test, 'hangup');
}


public function test_MAX_LENGTH_should_deserialize_to_string() {
    $test = TranscribeReason::MAX_LENGTH;
    $this->assertEquals($test, 'maxLength');
}


public function test_DIGIT_should_deserialize_to_string() {
    $test = TranscribeReason::DIGIT;
    $this->assertEquals($test, 'digit');
}


public function test_NO_INPUT_should_deserialize_to_string() {
    $test = TranscribeReason::NO_INPUT;
    $this->assertEquals($test, 'noInput');
}


}
