<?php

/**
 * UpdateConferenceRequestStatusTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  FreeClimb\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FreeClimb API
 *
 * FreeClimb is a cloud-based application programming interface (API) that puts the power of the Vail platform in your hands. FreeClimb simplifies the process of creating applications that can use a full range of telephony features without requiring specialized or on-site telephony equipment. Using the FreeClimb REST API to write applications is easy! You have the option to use the language of your choice or hit the API directly. Your application can execute a command by issuing a RESTful request to the FreeClimb API. The base URL to send HTTP requests to the FreeClimb REST API is: /apiserver. FreeClimb authenticates and processes your request.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@freeclimb.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto-generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace FreeClimb\Api\Test\Model;

use FreeClimb\Api\Model\UpdateConferenceRequestStatus;
use PHPUnit\Framework\TestCase;

/**
 * UpdateConferenceRequestStatusTest Class Doc Comment
 *
 * @category    Class
 * @description New status of the conference. Valid values: &#x60;empty&#x60; or &#x60;terminated&#x60;. For more information, see **Status Parameter** below.**
 * @package     FreeClimb\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UpdateConferenceRequestStatusTest extends TestCase
{
    protected $UpdateConferenceRequestStatus;

    /**
     * Test "UpdateConferenceRequestStatus"
     */
    public function setUp() : void
    {
        $this->UpdateConferenceRequestStatus = new UpdateConferenceRequestStatus();
    }

public function test_EMPTY_should_deserialize_to_string() {
    $test = UpdateConferenceRequestStatus::EMPTY;
    $this->assertEquals($test, 'empty');
}


public function test_TERMINATED_should_deserialize_to_string() {
    $test = UpdateConferenceRequestStatus::TERMINATED;
    $this->assertEquals($test, 'terminated');
}


}
